#!/usr/bin/env python
import gdas
station    = 'fribourg01'
start_time = '2016-11-03-17'
end_time   = '2016-11-03-18'
datapath   = '/Volumes/NURI-GNOME/GNOMEDrive/gnome/serverdata/'
ts_data,ts_list,activity = gdas.magfield(station,start_time,end_time,rep=datapath,resample=512)
#gdas.wavelet(ts_data)
#gdas.plot_activity(activity)
#gdas.plot_time_series(station,ts_list,seglist=activity)
#gdas.plot_asd(station,ts_list)
#gdas.plot_whitening(station,ts_list,activity)
psd_segment_length = 60
psd_segment_stride = 30
psd_estimation     = 'median-mean'
window_fraction    = 0
tile_fap           = 1e-5
channels           = 256
gdas.excess_power(ts_data,psd_segment_length,psd_segment_stride,psd_estimation,window_fraction,tile_fap,station,nchans=channels)
gdas.plot_triggers()
