#!/usr/bin/env python

import gdas

"""
This script is an example on how to run gdas using all the built-in
modules of the gdas package.
"""

# Look at each argument
args    = gdas.utils.arguments.construct_args()
station = args.station
start   = args.analysis_start_time
end     = args.analysis_end_time

# Convert to GPS time and retrieve data
start_time,end_time = gdas.utils.retrieve.convertdate(start,end)
data = gdas.utils.retrieve.magfield(station,start_time,end_time)

